EBIvariation/eva-web

src/js/variant-widget/eva-variant-widget-panel.js
src/js/variant-widget/eva-variant-widget.js
src/js/views/eva-variant-view.js
tests/mocha/variant_browser.js

EVA-389:dbSNP links in Variant Browser must be different for ss and rs

---

Gruntfile.js
bower.json
src/index.html
src/js/clinvar/eva-clinical-widget-panel.js
src/js/clinvar/eva-clinvar-widget.js
src/js/eva.js
src/js/study-browser/eva-study-browser-widget-panel.js
src/js/variant-widget/eva-variant-widget-panel.js
src/js/variant-widget/eva-variant-widget.js
src/js/views/eva-gene-view.js
src/js/views/eva-study-view.js
src/js/views/eva-variant-view.js

EVA-429: Google analytics 

---

src/js/clinvar/eva-clinvar-assertion-panel.js
src/js/variant-widget/eva-variant-widget.js

the clinical assertion tab was broken. Not displaying anything.

EVA-660: Clinical Browser Clinical Assertion tab broken

---

.gitmodules
Gruntfile.js
package.json
src/index.html

ebi framework version 1.1 added as submodule to server files locally and grunt build process updated

EVA-605:Web performance improvement: Caching

---

package.json
tests/mocha/config.js

website grunt build process failing. grunt andnode modules updated in the package.json file

EVA-702: website build process update

---

src/js/eva-manager.js
tests/mocha/all_page.js
tests/mocha/clinical_browser.js
tests/mocha/clinvar_bottom_panel_tests.js
tests/mocha/config.js
tests/mocha/gene_view.js
tests/mocha/home_page.js
tests/mocha/study_view.js
tests/mocha/variant_browser.js
tests/mocha/variant_browser_bottom_panel_tests.js
tests/mocha/variant_view.js

After upgrading node modules chai.expect is not working with selenium. 
Need to alter test cases which are using chai.expect

EVA-715: web tests chai.expect issue fixed and updated

---

Gruntfile.js
bower.json
package.json
src/index.html
src/js/views/eva-study-view.js

File table stats error makes study view not rendered.

EVA-733: Study View files table error

---

src/css/eva.css
src/index.html
src/js/views/eva-variant-view.js

Variant view horizontal menu added.

EVA-684: Variant View left menu is missing

---

src/js/clinvar/eva-clinical-widget-panel.js

The version of ClinVar referenced in the Clinical Browser must be updated to 04-2017.

EVA-777: Update ClinVar version in Clinical Browser

---

.travis.yml
Gruntfile.js
src/index.html
src/js/clinvar/eva-clinvar-annotation-panel.js
src/js/eva-config.js
src/js/eva.js
src/js/study-browser/eva-study-browser-grid.js
src/js/study-browser/eva-study-browser-widget-panel.js
src/js/variant-widget/eva-variant-widget-panel.js
src/js/variant-widget/eva-variant-widget.js
src/js/variant-widget/filters/eva-annotation-version-filter-form-panel.js
src/js/variant-widget/filters/eva-form-panel.js
src/js/views/eva-variant-view.js
tests/acceptance/variant_browser.js
tests/unit/variant_browser.js

Add a filter by annotation version to the left sidebar of the variant browser.

EVA-798: Implement filters at website level

---

src/js/eva-config.js
src/js/study-browser/eva-study-browser-filter-form-panel.js
src/js/study-browser/eva-study-browser-grid.js
src/js/study-browser/eva-study-browser-widget-panel.js
src/js/variant-widget/eva-variant-widget-panel.js
src/js/variant-widget/eva-variant-widget.js
src/js/variant-widget/filters/eva-species-filter-form-panel.js
src/js/views/eva-study-view.js
src/js/views/eva-variant-view.js

In study Browser Page Webpage studies/all web service called twice. it should be fixed.

EVA-792: Study Browser page api called twice

---

src/js/clinvar/eva-clinical-widget-panel.js
src/js/clinvar/eva-clinvar-annotation-panel.js
src/js/eva.js
src/js/variant-widget/eva-variant-widget-panel.js
src/js/variant-widget/eva-variant-widget.js
tests/acceptance/all_page.js
tests/acceptance/clinical_browser.js
tests/acceptance/variant_browser.js
tests/acceptance/variant_browser_bottom_panel_tests.js

Some of the regions set by default do not display enough variants to be interesting, and others are so long that the queries often time out. Set the following defaults for the species below to make them more useful:
Human / GRCh38 : 13:32315474-32400266 (BRCA2 coordinates)
Human / GRCh37: 13:32889611-32973805 (BRCA2 coordinates, update Clinical Browser to match)
Mosquite / AaegL3 : supercont1.18:100000-500000

EVA-900: More illustrative regions in Variant Browser

---

src/js/dbSNP-import/dbSNP-import-progress.js

Instead of taking the string indicating on which date a dbSNP task was finish as it is, format it as dd/mm/yyyy.

EVA-946 Showing formatted date

---

Gruntfile.js
bower.json
package.json
src/js/variant-widget/eva-variant-widget-panel.js

Fixed zebrafish default search region, and others modified in different way: shortened, slightly lengthened, added, etc. Version bumped to 3.9.1.

EVA-1063 EVA-1067 Improved default search regions

---

Gruntfile.js
bower.json
package.json
src/index.html

EVA-1107 Fixed elixir banner

---

src/js/eva-google-analytics.js
tests/acceptance/config-manager.js
tests/acceptance/variant_browser.js

Modified to anonymize IPs in google analytics according to the GDPR

EVA-1225 Anonymize user IP in Google Analytics

---

Gruntfile.js
bower.json
package.json
src/js/variant-widget/eva-variant-widget-panel.js
tests/acceptance/variant_browser.js

Default regions for brown mustard, fruit fly, grape, guinea pig and sunflower.
Fix single failing test.

General maintenance

---

src/js/eva-config.js

To be merged after the imports scheduled for Sprint 77 are complete

EVA-1388 Species added to SNP search for the week of Oct 19, 2018

---

Gruntfile.js
README.md
src/js/eva-manager-config.js
src/js/eva.js
src/js/variant-widget/eva-variant-widget-panel.js
src/js/variant-widget/eva-variant-widget.js
src/js/variant-widget/filters/eva-species-filter-form-panel.js
tests/acceptance/variant_browser.js
tests/acceptance/variant_view.js

Add `export to VCF` functionality (beta) to the variant browser

EVA-1113 VCF dumper public beta deployment

---

src/index.html

Added instructions for the process spreadsheet > tsv > vcf.
Split the ped > vcf process into another subsection.
Link to example / template on Google Sheets.
Slightly better structured HTML.

EVA-1338 Add tsv > vcf instructions for xlsx files

---

src/index.html

See http://wwwint.ebi.ac.uk/eva/EVA-1525/?API

EVA-1525 - Added note on rate limiting to the API page

---

src/index.html
src/js/eva-config.js
src/js/views/eva-multi-variant-view.js
src/js/views/eva-variant-view.js
tests/acceptance/variant_view.js

* Variants in EVA
* Single variant view - http://wwwdev.ebi.ac.uk/eva/EVA1683/?variant&accessionID=rs123&species=hsapiens_grch37&assemblyAccession=GCA_000001405.1
* Multiple variant view - http://wwwdev.ebi.ac.uk/eva/EVA1683/?variant&accessionID=rs123,rs345&species=hsapiens_grch37&assemblyAccession=GCA_000001405.1
* Variants in accessioning (should work after EVA-1685 is complete)
* Single variant view - http://wwwdev.ebi.ac.uk/eva/EVA1683/?variant&accessionID=rs2913&species=hsapiens_grch38&assemblyAccession=GCA_000001405.27
* Multiple variant view - http://wwwdev.ebi.ac.uk/eva/EVA1683/?variant&accessionID=rs2913,rs2532&species=hsapiens_grch38&assemblyAccession=GCA_000001405.27
* Variants neither in EVA nor accessioning
* Single variant view - …

EVA-1683 - Support human SNP search in the UI

---

src/js/views/eva-variant-view.js

Merge after EBIvariation/eva-accession#296

EVA-2237 Support multiple assemblies in variant view

---

src/js/views/eva-variant-view.js

It should be the same as the start.

EVA-3195: Fix variant end coordinate for insertion 

---

src/css/eva.css
src/index.html

Changes deployed in dev : [https://wwwdev.ebi.ac.uk/eva/EVA-3759](https://wwwdev.ebi.ac.uk/eva/EVA-3759/?Submit-Data)

EVA-3759 Update Submit Page
