- src/css/eva.css
It is not possible to see what variant is selected in the top table when browsing the in-depth data.
Fix is to highlight row selected in the top table.
> EVA-611: variant browser css changes

- src/js/views/eva-study-view.js
Whilst we resolved the on-going EVAPRO taxonomy issue (ELOAD-185), please can we hard code the following studies in the website to show with accession GCA_000001405.18 (GRCh38):
PRJEB15384
PRJEB15198
PRJEB15197
All other human studies should be shown with GRCh37.
> EVA-662: Hard Code Assemblies For GRCh38 Studies

- src/js/clinvar/eva-clinical-widget-panel.js
When searching for RCV000035325 at the clinical browser. If one then selects the gene view via the MSH6 hyperlink, and then back to the Clinical Browser, the RCV changes.
> EVA-666: Back Button From Clinical Gene View to Clinical Browser changes search

- Gruntfile.js
- src/index.html
- src/js/variant-widget/eva-variant-files-panel.js
- src/js/variant-widget/eva-variant-widget-panel.js
- src/js/variant-widget/eva-variant-widget.js
- src/js/views/eva-variant-view.js
- tests/mocha/config.js
When clicking on the Variant View link for a single variant, the REST endpoint variants/{variantId}/info is called.
On the other hand, when selecting a variant in the Variant Browser to view the details in the bottom tab, the segments/{segmentId}/variants endpoint is called, which can lead to problems if more than one allele has been reported in that position.
The variants/{variantId}/info must be used in that case.
> EVA-721: Use single variant info in Variant Browser bottom tab

- src/js/variant-widget/eva-variant-widget.js
Steps to reproduce:
Execute a Variant Browser search
Select a variant
Click on the "Files" or "Population Statistics" bottom tabs
The alignment of the first row in the top table is not correct
> EVA-682:First row of Variant Browser top table alignment broken after clicking on bottom tabs

- src/js/clinvar/eva-clinvar-annotation-panel.js
- src/js/variant-widget/eva-variant-widget.js
This column should be renamed to "Ensembl Transcript Biotype", as it is currently unclear to what this refers to.
Also the order of the columns should be changed so that the Biotype column comes after the "Ensembl Transcript ID" column.
> EVA-664:annotation table biotype column renamed

- src/index.html
delete the "EVA Clinical Submissions" and the text below from this page: http://www.ebi.ac.uk/eva/?Templates
> EVA-726: Delete Clinical Submissions Templat

- src/js/clinvar/eva-clinvar-annotation-panel.js
- src/js/variant-widget/eva-variant-files-panel.js
- src/js/variant-widget/eva-variant-genotype-grid-panel.js
- src/js/variant-widget/eva-variant-population-stats-panel.js
I don't think it is obvious to people that the 'i" icons are able to be hovered over for more information. This comes from a number of workshops including today's at University of Cambridge. I think it is better to remove the bubbles and print the text. For example, the VEP and e! versions that are shown when hovering over the "i" in the Annotation tab.
> EVA-665: Remove Bubbles in Variant Browser and instead print text

- src/index.html
On the API page, the link to the Swagger documentation should point to https://hostname/eva/webservices/rest/swagger-ui.html instead of http://hostname/eva/webservices/api/.
> EVA-762: Link to Swagger documentation broken

- Gruntfile.js
- bower.json
- package.json
- src/js/variant-widget/eva-variant-files-panel.js
- src/js/variant-widget/eva-variant-genotype-grid-panel.js
- src/js/variant-widget/eva-variant-population-stats-panel.js
- src/js/variant-widget/eva-variant-widget-panel.js
The EVA variant browser displays hyperlinks to ERZ folder on the EVA FTP. We know that some of these hyperlinks are wrong.
In order to keep the Variant Browser and Study Browser functionalities separate we shall remove the FTP links from the Files, Genotypes and Population Statistics tabs. The remaining links to 'download data' shall be to the EVA Study Browser pages.
> EVA-762: Remove ERA FTP links from Variant Browser tabs

- src/js/beacon-form/eva-beacon-form.js
- src/js/clinvar/eva-clinical-widget-panel.js
- src/js/study-browser/eva-study-browser-widget-panel.js
- src/js/variant-widget/eva-variant-widget-panel.js
- tests/acceptance/clinical_browser.js
- tests/acceptance/config-manager.js
- tests/acceptance/study_browser.js
- tests/acceptance/study_view.js
In order to make more clear the intention of the search forms, the 'Submit' text has been replaced with 'Search' in the following pages:
* Study browser
* Variant browser
* Clinical browser
* GA4GH beacon
> EVA-909 'Submit' text in buttons replaced with 'Search'

- README.md
- tests/acceptance/study_browser.js
- tests/acceptance/variant_browser.js
- one test assumed that in the ID column could appear subsnps. Currently only rs ids can appear there.
- Another one assumed that a study has only one type. This is not correct.
- Added a bit of information about the tests in the README.
> Fix travis builds

- Gruntfile.js
- bower.json
- package.json
- src/js/variant-widget/eva-variant-browser-grid.js
- src/js/variant-widget/eva-variant-widget.js
- tests/unit/variant_browser.js
The function _findWhere returns undefined if a score for a source (sift or polyphen) is not found. The call to '.score' over that undefined object was causing the function terminating abruptly without returning any score. This has been fixed, storing the result of _findWhere in a local variable and checking if is undefined before accessing its attributes.
> EVA-1048 Fixed bug in visualization of variants with a single substitution score

- src/js/variant-widget/eva-variant-browser-grid.js
After an erroneous call in the variant search, a correct call with no results was no refreshing the screen, and the error message was not being replaced by a 'No variants to display' one
> Fixed bug introduced in the last commit

- tests/acceptance/config-manager.js
- tests/acceptance/variant_browser.js
Added click action on data protection banner for automated tests
We are leaving this line `driver.findElement(By.xpath("//div[@id='cookie-dismiss']//button[@class='close-button']")).click();` because the old banner is still shown in the web site after the new banner is dismissed.
> EVA-1219 GDPR privacy notices on website and submissions

- src/index.html
Link added to notify users how their personal will be used before they actually send it. Also links to submission stages for easier linking from RT replies.
Additionally, removed reference to experiments as we don't accept those (ENA does).
> EVA-1219 GDPR privacy notice on website

- src/css/eva.css
- src/index.html
- src/js/dbSNP-import/dbSNP-import-progress.js
- tests/acceptance/dbSNP_import.js
dbSNP Import Progress usability changes.
Columns deleted: `All variants match INSDC assembly`, `Suitable for Variant Browser`, `Current dbSNP accessions searchable`  
New Columns: `Current RS IDs`, `Synonymous RS IDs`
> EVA-1226 Address dbSNP import progress report usability issues

- src/js/eva-manager-config.js
- src/js/variant-widget/eva-variant-widget-panel.js
- tests/acceptance/variant_browser.js
- Changed WS endpoint used to filter by variant id
- Replace whitespaces (including tabs or line jumps) by "," in the variant id search box
> EVA-924 Allow multiple ids in search

- Gruntfile.js
- src/js/eva-manager-config.js
- src/js/study-browser/eva-study-browser-widget-panel.js
- src/js/views/eva-study-view.js
- tests/acceptance/study_view.js
Requires https://github.com/EBIvariation/eva-ws/pull/95 to be merged and deployed first.
Using DGVa REST API in study browser and view, instead of EVA's. A new "manager" created that basically replicates the behavior of the EVA one, and displays unified for both archives.
> EVA-1263 Study browser / view pointing to DGVa API

- src/index.html
- src/js/eva.js
The EVA Twitter handle is 'evarchive'. Maybe 'EBIvariation' was used at the beginning and the redirection was deprecated?
> EVA-1366 Twitter handle corrected

- src/js/variant-widget/eva-variant-widget.js
- tests/acceptance/variant_browser.js
Changes made in **Variant View**
- Variant ID column is now showing the `mainId`
- Changed ensembl link url to support all species
- Export as CSV functionality fixed to not omit columns when a variant has an empty value for a column (reference, alternate, mainId, consequenceTypes)
> EVA-981 Display main variant identifier in Variant Browser top table

- src/js/dbSNP-import/dbSNP-import-progress.js
- tests/acceptance/dbSNP_import.js
- The number is species shown in the dbsnp import progress report was changed from 80 to 190.
- The column `Current SS IDs` was added to the report
- The order of the report is: Current RS IDs (DESC), Current SS IDs (DESC), Common name (ASC)
> EVA-1268 Modify dbsnp import progress report with number of species to show and new column for ss count

- src/js/eva-config.js
- src/js/variant-widget/eva-variant-population-stats-panel.js
- src/js/views/eva-variant-view.js
eva-variant-population-stats-panel.js - Show separate heading for each ref/alt
eva-variant-view.js - explicitly check null values to avoid  variant view rendering interrupted by javascript errors
> EVA-1388 - Fixed taxonomyId for Cottonwood and variant view fixes

- src/js/dbSNP-import/dbSNP-import-progress.js
- src/js/eva-manager-config.js
Populate the dbSNP import progress report using the new (simplified) response structure from https://github.com/EBIvariation/eva-ws/pull/109, which supports multiple assemblies per database.
> EVA-1465 Bugfix for only one record per database shown in the dbSNP import progress report

- src/js/eva-config.js
Fixed by making uniq over two fields, not one.
(The build is failing; however, it was failing before as well.)
> EVA-1495 — Fix species list in the SNP search dropdown in the homepage

- src/js/eva-config.js
- src/js/variant-widget/filters/eva-species-filter-form-panel.js
- src/js/views/eva-variant-view.js
eva-config.js - Updates to support multiple taxonomies for the same species
eva-species-filter-form-panel.js - Updates to use only one of the taxonomy names in case of "Rice" and "Rice (Japanese)"
eva-variant-view.js - When fetching SS IDs from the /submitted endpoint in the identifier webservice, match the assembly in the response against the assembly for which the search was invoked.
> EVA-1481 - Match assembly with the request fetching assoc. SS in variant view

- src/js/views/eva-variant-view.js
**Merged variants** now display a message which instructs the user that the requested variant ID has been merged and that they have been redirected to the target variant. (Previously: user was silently redirected without showing any message, see [link](https://www.ebi.ac.uk/eva/?variant&accessionID=rs1106670930&species=athaliana_tair10).)
**Deprecated variants** now display summary information, as well as a message which instructs the user that the requested variant ID has been deprecated and should not be used. (Previously: deprecated variants returned "No Data Available", see [link](https://www.ebi.ac.uk/eva?variant&accessionID=rs119027987&species=mtruncatula_MedtrA17_3.5).)
> EVA-1488 — More clear display of merged and deprecated events

- tests/acceptance/variant_browser.js
- tests/acceptance/variant_view.js
In the original PR https://github.com/EBIvariation/eva-web/pull/147 I had to temporarily modify the expected results of two tests because the staging environment was outdated and not returning the correct values. In the recent PR https://github.com/EBIvariation/eva-web/pull/148 those tests have failed because the staging environment has (apparently) been updated. We can now roll back these two tests.
In fact, only one of these tests needed the roll back; the error in the other one turned out to be caused by the race condition in the test itself (before refactoring) rather than the staging environment issue.
> EVA-1522 — Roll back tests after staging environment update

- src/js/dbSNP-import/dbSNP-import-progress.js
Right now, both the RS ID and SS ID percentage of completion are ordered for sorting, meaning that in practice the alphabetical ordering on names is applied only for 100% on both. Using only the RS ID and the name allows to form clusters for 100%, 99.99%, etc.
Therefore, the dbSNP import progress report is no longer ordered by SS ID %.
> EVA-1624 Change dbSNP import report ordering to only by RS ID % and common name

- tests/acceptance/variant_browser.js
Those two tests are the only ones using Mosquito / AgamP3 genome in the variant browser. Here's the sequence of events for both of them:
```javascript
// Variant browser is reset before the start of the test
variantBrowserResetAndWait(driver);
// Mosquito / AgamP3 genome is chosen
driver.findElement(By.xpath("//li[text()='Mosquito / AgamP3']")).click();
driver.findElement(By.xpath("//li[text()='Mosquito / AgamP3']")).click();
// Waiting for the variants to be loaded before doing anything else
waitForVariantsToLoad(driver);
```
The problem is that `waitForVariantsToLoad(driver)` expects to first see a loading mask to appear (optionally, because it knows it might just miss one) and then for at least one variant to load. However, when you select this mosquito genome in the variant browser, …
> EVA-1638 — Fix two acceptance tests using Mosquito / AgamP3 genome

- src/js/variant-widget/eva-variant-genotype-grid-panel.js
- tests/acceptance/variant_browser.js
- tests/acceptance/variant_browser_bottom_panel_tests.js
* Update formatAlleles extension function to support haploid genotypes like "0" or "1"
* Add acceptance test for haploid genotypes
> EVA-1374 - Support haploid genotypes in the Variant Browser

- src/js/dbSNP-import/dbSNP-import-progress.js
Note: suggest to merge this after #160 and #159 .
- percentages include unmapped variants available in FTP
- human incompleteness reasons
- some species don't have build because they are unmapped
temporary preview: https://wwwint.ebi.ac.uk/eva/EVA-1722/?dbSNP-Import-Progress
> EVA-1722 Less 0% in the report progress page

- .travis.yml
- package.json
- src/index.html
- src/js/eva-config.js
- src/js/rs-release/rs-release.js
- src/js/views/eva-multi-variant-view.js
- src/js/views/eva-variant-view.js
- tests/acceptance/config-manager.js
- tests/acceptance/dbSNP_import.js
- tests/acceptance/home_page.js
- tests/acceptance/multi_variant_view.js
- tests/acceptance/rs_release.js
- tests/acceptance/variant_browser.js
- tests/acceptance/variant_view.js
This PR is still work in progress, **do not merge**. Is not marked as draft because I need travis to run
> EVA-2218 Fix variant view by variant info and fix tests

- src/index.html
- src/js/eva.js
This is only an empty tab and it assume we will manually copy the Javascript file `genotype_view.js` in the js directory but if that's done in the deployment it should work.
> EVA-3142 - Enable Genotype view integration
